### ISSUE TITLE
Strange default language

### ISSUE THREAD

**Issue by rdscorreia74** [clericJ/snmp_scanner#1]
Hi,
Just installed this tool.
After opening the tool it seems to automatically show up in Cyrilic or some strange language to me.
Is there any way to use the tool in English?
Thanks in advance.
Cheers

**Comment by clericJ** [comment]
Hi, please test this version of the application: https://sourceforge.net/projects/snmp-scanner/files/SNMPScannerSetup.zip/download

**Comment by rdscorreia74** [comment]
Hi @clericJ 
Sorry for taking so long to reply but I completely lost track of this browser tab.
Now that I have found it, I downloaded from your link and I can confirm that it's working great in English.
So thanks a lot.
Cheers
